#  Authors 
#  Alexander Freudenberg, alexander.freudenberg@stads.de

#  Copyright (C) 2023 Alexander Freudenberg

#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.


using Base;
using Random;
using LinearAlgebra;
using CSV;
using DelimitedFiles;
using DataFrames;
using BenchmarkTools;
using LoopVectorization;

# =====================
# Global definitions
# =====================

ROOT_DIR = string(@__DIR__) * "/../.."

MODULE_PATH = ROOT_DIR * "/src/bindings/Julia/miraculix.jl"
LIBRARY_PATH = ROOT_DIR * "/src/miraculix/miraculix.so"
DATA_DIR = ROOT_DIR * "/data"
LOG_DIR = DATA_DIR * "/logs"

# Control miraculix verbosity
ENV["PRINT_LEVEL"] = "1";

OMP_NUM_THREADS = ENV["OMP_NUM_THREADS"];
println("OMP threads set to $OMP_NUM_THREADS")

include(MODULE_PATH)

# =====================
# Auxiliary functions
# =====================
function multiply_ld(obj_ref::Ref{Ptr{Cvoid}}, snps::Int, indiv::Int, B::Matrix{Float64})
    # Calculate SNPs times Matrix
    Z_vec = miraculix.dgemm_compressed.dgemm_compressed_main(false, obj_ref, B, n_snps, n_indiv)
    # Calculate Individuals times Matrix
    ZtZ_vec = miraculix.dgemm_compressed.dgemm_compressed_main(true, obj_ref, Z_vec, snps, indiv)
    return ZtZ_vec
end
function randomized_range_finder(obj_ref::Ref{Ptr{Cvoid}}, snps::Int, indiv::Int, l::Int, q::Int)
    # This function implements the randomized range finder from Halko et al., 2011
    ncol = snps
    Omega = randn(Float64, (ncol, l))
    Y = multiply_ld(obj_ref, snps, indiv, Omega)
    QRj = qr(Y).Q |> Matrix
    if q > 0
        for _ in range(1,q)
            ZtZ_Q = multiply_ld(obj_ref, snps, indiv, QRj)
            QRj = qr(ZtZ_Q).Q |> Matrix
            ZtZ_Q = multiply_ld(obj_ref, snps, indiv, QRj)  #G * QRj
            QRj = qr(ZtZ_Q).Q |> Matrix
        end
    end
    return QRj
end # function

function randomized_eigen(obj_ref::Ref{Ptr{Cvoid}}, snps::Int, indiv::Int, n::Int, p::Int = 40, q::Int = 2)
    # For documentation of hyperparameters, see Halko et al., 2011
    QR_rf = randomized_range_finder(obj_ref, snps, indiv, n + p, q)
    ZtZ_Q = multiply_ld(obj_ref, snps, indiv, QR_rf)
    EV = eigvecs(transpose(QR_rf) * ZtZ_Q)
    U = QR_rf * EV

    return U
end # function

function randomized_snp_pca(plink::Matrix{UInt8}, plink_transposed::Matrix{UInt8}, snps::Int, indiv::Int, n::Int, p::Int = 40)
    obj_ref = miraculix.dgemm_compressed.init_compressed(plink, plink_transposed, snps, indiv, freq, n+p)

    U = randomized_eigen(obj_ref, snps, indiv)
    PC = miraculix.dgemm_compressed.dgemm_compressed_main(false, obj_ref, U, snps, indiv)

    miraculix.dgemm_compressed.free_compressed(obj_ref)
    return PC
end

# =====================
# Main
# =====================

miraculix.set_library_path(LIBRARY_PATH)
miraculix.load_shared_library()
miraculix.dgemm_compressed.set_options(use_gpu=true, verbose=0)

# We assume that genotype data has been generated by the R package MoBPS 
data_file = DATA_DIR * "/mobps_simulation.bed"

# Read-in data from PLINK binary format
@info "Reading in data from $data_file"
wtime = @elapsed begin
    plink, freq, n_snps, n_indiv = miraculix.read_plink.read_bed(data_file, coding_twobit = true, calc_freq = true, check_for_missings = false)
    pheno = CSV.read(DATA_DIR * "/mobps_simulation.fam", delim = ' ', DataFrame, header = 0)[:,6]
end
@info "Importing data required $(round(wtime,digits=3)) seconds."

if (length(ARGS) > 0) && (ARGS[1] == "test")
    n_snps = 1000
    plink = plink[:,1:n_snps]
    freq = freq[1:n_snps]
end

@info "Transposing PLINK matrix."
GC.gc()
wtime = @elapsed begin
    plink_transposed = miraculix.compressed_operations.transpose_genotype_matrix(plink, n_snps, n_indiv)
end
@info "Transposing required $(round(wtime,digits=3)) seconds"


# Calculate the GRM in miraculix
@info "Calculating the genomic relationship matrix"
GC.gc()
wtime = @elapsed begin
    G = miraculix.crossproduct.grm(plink_transposed, n_snps, n_indiv, is_plink_format = false, allele_freq = vec(freq), do_scale = true)
end
@info "GRM calculation required $(round(wtime,digits=3)) seconds"


# Convert twobit encoding back to PLINK
@info "Converting matrix back to PLINK format for phenotype multiplication"
wtime = @elapsed begin
    vmapt!(miraculix.read_plink.convert_twobit2plink, plink, plink)
    vmapt!(miraculix.read_plink.convert_twobit2plink, plink_transposed, plink_transposed)
end
@info "Format conversion required $(round(wtime,digits=3)) seconds"

# Multiply eigenvectors by SNP matrix to obtain principal components of SNPs
@info "Calculating principal components"
wtime = @elapsed begin
    princ_comps = randomized_snp_pca(plink, plink_transposed, n_snps, n_indiv, 10)
end

# Calculate BLUE for beta through the formula
# \hat{beta} = (X^T (lambda I + G)^{-1} X)^{-1} X^T (lambda I + G)^{-1} Y
# with lambda = sigma_u^2 / sigma_epsilon^2 
# We assume a known heritability of 0.5 and hence lambda = c sigma_g^2/sigma_epsilon^2 = c 
# with c = 2 p^T (1-p)
var_comp_ratio = 2 * transpose(freq) * (1.0 .- freq)
var_g_ratio = 1.0

# Design matrix of fixed effects
X = hcat(ones(Float64, (n_indiv, 1)), princ_comps)
Y = pheno
rhs_matrix = hcat(X, Y)
