name: C/C++/CUDA CI

on:
  workflow_call:
  
jobs:
  build_gpu:
    runs-on: GPU
    steps: 
      - name: make
        run: |
          make -C src
  
  call_shutdown_workflow:
    name: Start shutdown workflow
    needs: build_gpu
    if: ${{ always() }}
    uses: ./.github/workflows/instance-stop.yml
