name: C/C++/CUDA CI

on:
  workflow_call:
  
jobs:
  build_gpu:
    runs-on: GPU
    steps: 
      - name: make
        run: |
          make -C src
  
  shutdown_instance:
    name: Shutdown instance
    runs-on: GPU
    if: ${{ always() }}
    steps:
      - run: |
          shutdown now
